### ISSUE TITLE
dont work command

### ISSUE THREAD

**Issue by majovec** [TonyDroidd/Infection#2]
command dont work :/

**Comment by ondraczsk** [comment]
majovce jsem admin na WallGuardu :D Mas tam ban xD

**Comment by majovec** [comment]
Tvl ondro toto neslouzi jako chat a navic me staci napat Olegovi a mam Pardon

**Comment by ondraczsk** [comment]
xD

**Comment by TonyDroidd** [comment]
Plugin is not finished.

**Comment by TonyDroidd** [comment]
Plugin is not finished.
